// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/blog/[handle]": InferRoute<import("./src/app/blog/[handle]/routeType").RouteType>;
    "/work/[handle]": InferRoute<import("./src/app/work/[handle]/routeType").RouteType>;
  }

  interface StaticRouter {
    "/about": StaticRoute;
    "/": StaticRoute;
  }
}
