enum Skills {
  "Figma" = "Figma",
  "Adobe" = "Adobe Creative Suite",
  "Next.js" = "Next.js",
  "Clerk" = "Clerk",
  "Typescript" = "Typescript",
  "Tailwind" = "Tailwind",
  "Radix" = "Radix",
  "Framer Motion" = "Framer Motion",
  "Storybook" = "Storybook",
  "Nest.js" = "Nest.js",
  "NX" = "NX",
  "Contentful" = "Contentful",
  "Postgres" = "Postgres",
  "React Admin" = "React Admin",
  "Vite" = "Vite",
  "Drizzle" = "Drizzle",
  "trpc" = "trpc",
  "TS-Rest" = "TS-Rest",
  "GraphQL" = "GraphQL",
  "i18Next" = "i18Next",
  "Auth0" = "Auth0",
  "React" = "React",
  "Prisma" = "Prisma",
  "Supabase" = "Supabase",
  "Material UI" = "Material UI",
  "AWS" = "AWS",
  "Tiptap" = "Tiptap",
}

export { Skills };
